import request from '../utils/request'
export const myStories = () => request.get('/stories/mine')
export const createStory = (data) => request.post('/stories', data)
export const deleteStory = (id) => request.delete('/stories/' + id)
export const submitAudit = (id) => request.post('/stories/' + id + '/submit')
export const updateStoryMeta = (id, data) => request.put('/stories/' + id, data)
export const requestDeleteStory = (id, reason) => request.post('/stories/' + id + '/delete-request', { reason })
export const validateStory = (id) => request.post('/stories/' + id + '/validate')
export const listNodes = (storyId) => request.get('/editor/stories/' + storyId + '/nodes')
export const listChoices = (nodeId) => request.get('/editor/nodes/' + nodeId + '/choices')
export const addNode = (storyId, data) => request.post('/editor/stories/' + storyId + '/nodes', data)
export const updateNode = (nodeId, data) => request.put('/editor/nodes/' + nodeId, data)
export const deleteNode = (nodeId) => request.delete('/editor/nodes/' + nodeId)
export const addChoice = (nodeId, data) => request.post('/editor/nodes/' + nodeId + '/choices', data)
export const updateChoice = (choiceId, data) => request.put('/editor/choices/' + choiceId, data)
export const deleteChoice = (choiceId) => request.delete('/editor/choices/' + choiceId)
