server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: storyworkshop

  profiles:
    active: dev

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Hong_Kong

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 20MB

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

app:
  upload:
    root-path: ../uploads
    cover-path: covers
    avatar-path: avatars
  cors:
    allowed-origins:
      - http://localhost:5173
      - http://127.0.0.1:5173